---
title: "Instruktionen zur Klausur"
format: 
  revealjs:
    auto-slide: 9000
    loop: true
    slide-number: true
    controls: true
    theme: [dark, css/custom.scss]
    footer: "Diese Folien: https://bit.ly/merk108"
---

## Herzlich Willkommen 🤗!
> In diesen Folien werden Ihnen alle relevanten Informationen zur Klausur angezeigt


. . .

<br>

::: {.callout-note}
## Wer soll wo hin?
* PO18 —> KIT Audimax
* PO22 
    * Nachname Aa - Fre —> PHKA 1.013
    * Nachname Fri - Hög —> PHKA 1.103
    * Nachname Hör - Mau —> PHKA 1.113
    * Nachname May - Rus —> PHKA 1.203
    * Nachname Sah - Zz —> KIT Audimax
:::

```{r}
# Change css to lecker PH green
if(!dir.exists("img"))
dir.create("img")
if(!dir.exists("css"))
dir.create("css")
fileConn<-file("css/custom.scss")
writeLines(c("/*-- scss:defaults --*/",
             "$link-color: #8cd000 !default;"), fileConn)
close(fileConn)
```

## Wie läuft die Klausur ab? {.smaller}
1) Sie kommen nach vorne und lassen Ihren Studierendenausweis kontrollieren und bekommen ein Nummernkärtchen
2) Sie besetzen jeden dritten Sitz in Ihrem Hörsaal (am Besten in der Mitte beginnen und nach außen auffüllen)
3) Sie stellen/legen Ihr Nummernkärtchen neben sich auf
4) Sie legen Ihren Studierendenausweis neben sich auf den Tisch
5) Sie schreiben sich in den für Sie zutreffenden moodle-Kurs ein
    * Klausur Psych/FoMe SoSe 23 - Ort: PHKA
    * Klausur Psych/FoMe SoSe 23 - Ort: KIT
6) Sie rufen die für Sie richtige Klausur auf    
7) Sie beantworten alle Fragen richtig 😉
8) Fragen können wir leider nur nach der Klausur beantworten
9) Bitte alle der Fairness halber bis 19:15 sitzen bleiben

## 
::: {.callout-note icon=false}

## Was ist erlaubt?
Digitale und analoge Quellen. Also Aufschriebe, Webpages (auch deren Suche via Suchmaschinen)
:::

::: {.callout-important icon=true}
## Was ist nicht erlaubt?
Kommunikation mit „intelligenten Entitäten“ (z.B. Menschen, Siri, ChatGPT, Alexa, …).
Lassen Sie also Mails, Chats, etc. geschlossen.
:::

::: {.callout-caution icon=true}
## Was passiert wenn Sie cheaten?
Um keine Störungen zu verursachen dokumentieren wir den Täuschungsversuch "still" über Ihr Platzkärtchen und verbuchen anschließend Ihre Studienleistung als nicht bestanden (dieses Vorgehen ist rechtssicher).
:::
